/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package galeria;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;


/**
 *
 * @author RC
 */
public class Galeria extends javax.swing.JFrame {

    /**
     * Creates new form Galeria
     */
    public Galeria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sistemaFicheiros = new javax.swing.JFileChooser();
        desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuFicheiro = new javax.swing.JMenu();
        ficheiroAbrir = new javax.swing.JMenuItem();

        sistemaFicheiros.setMultiSelectionEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha Galeria");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        menuFicheiro.setText("Ficheiro");

        ficheiroAbrir.setText("Carregar Imagens");
        ficheiroAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheiroAbrirActionPerformed(evt);
            }
        });
        menuFicheiro.add(ficheiroAbrir);

        barraMenu.add(menuFicheiro);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ficheiroAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheiroAbrirActionPerformed
       if(sistemaFicheiros.showOpenDialog(rootPane) == 0){
           //criar array com total de ficheiros seleccionados
           File[] imagens = sistemaFicheiros.getSelectedFiles();
           
           //percorrer array de ficheiros e extrair ficheiro a ficheiro
           for(int i=0; i<imagens.length; i++){
               
               //label - contém imagem
               JLabel foto = new JLabel(
                    new ImageIcon(imagens[i].getPath())
               );
               
               //scoll - contém a label
               JScrollPane scroll = new JScrollPane(foto);
               
               //criar frame interna
               JInternalFrame janelaInterna =
                       new JInternalFrame(imagens[i].getName(), true, true, true, true);
               janelaInterna.setLayout(new BorderLayout());
               
               //adicionar scroll (que já contém label com imagem) à janela interna
               janelaInterna.add(scroll, BorderLayout.CENTER);
               janelaInterna.setSize(640, 480);
               janelaInterna.setVisible(true);
               
               //adicionar janela ao DesktopPane
               desktop.add(janelaInterna);
           }
       }
    }//GEN-LAST:event_ficheiroAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem ficheiroAbrir;
    private javax.swing.JMenu menuFicheiro;
    private javax.swing.JFileChooser sistemaFicheiros;
    // End of variables declaration//GEN-END:variables
}
