/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelaEditor;


/**
 *
 * @author tiago
 */
public class JanelaPreVisualizar extends javax.swing.JDialog {

    /**
     * Creates new form JanelaPreVisualizar
     */
    public JanelaPreVisualizar(java.awt.Frame parent, boolean modal, String texto) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        jEditorPanePreVisualizar.setContentType("text/html");
        jEditorPanePreVisualizar.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        scroll = new javax.swing.JScrollPane();
        jEditorPanePreVisualizar = new javax.swing.JEditorPane();

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pre-Visualizar");
        setMinimumSize(new java.awt.Dimension(450, 350));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(850, 650));
        setSize(new java.awt.Dimension(850, 650));

        scroll.setPreferredSize(new java.awt.Dimension(650, 450));
        scroll.setViewportView(jEditorPanePreVisualizar);

        getContentPane().add(scroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JEditorPane jEditorPanePreVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}
